title: "Salary Survey Questions"
description: "A clickable wireframe of the WTD Documentation Salary Survey Questions, for gathering community feedback."

plugins:
  - jemoji

exclude: ["_plugins"]

url: "https://writethedocs.github.io"
baseurl: "/salary-survey"  