name: Deploy Live Site

on:
  push:
    branches:
      - main  # Runs only when pushing to main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Ruby and Jekyll
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'

      - name: Install Jekyll and Plugins
        run: |
          gem install jekyll jemoji

      - name: Build Jekyll site
        run: jekyll build --destination _site

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages  # ✅ Live site deploys to root of gh-pages
          publish_dir: ./_site
          keep_files: true  # ✅ Keeps PR previews in their own subfolders
